### PR TITLE
Bringing in current `dev` branch to `main` with new CI and bugfix

### PR DESCRIPTION
**Pull request by freemansw1**
I'd like to merge `dev` with `main` so that we have the new CI via GitHub actions (#68) on the `main` branch. This will also bring in the bugfix (#66) to this branch. I don't think we need a release yet, but it would be good to get this current.

### CODE REVIEW

**Comment by freemansw1** [comment]
Note that the travis-ci integration no longer works. I've deleted the webhook, but it will still show that check as not finished for this PR. It should be resolved for future PRs.

**Review by w-k-jones — APPROVED** [review]
Looks good, happy for this to be merged

**Comment by fsenf** [comment]
PR looks good also from my side. Merging is somehow stuck ... not sure if Will just forgot to press the button or if the crashing travis CI builds up a small wall for us. I will try to force the PR merge now ...

**Comment by fsenf** [comment]
OK, merge was only possible with admin privileges ... Hope that I didn't oversee any other aspect ...

**Pull request merged**
