### PR TITLE
Bug fix for spectral filtering feature

### PR DESCRIPTION
**Pull request by JuliaKukulies**
Bug fix for ```spectral_filtering``` in ```utils/general.py```  that belongs to PR #65

### CODE REVIEW

**Review by w-k-jones — COMMENTED** [review]
Happy to approve this, but it should probably be made clear that this is also formatting all of the v2.0-dev branch. I have no problem with this, but it's probably best to make anyone else working on v2.0-dev aware of this!

**Comment by JuliaKukulies** [comment]
Wonderful, thanks! And apologies that the formatting came in the same commit. I realized that we have to be a bit careful with the formatting so the review does not get too messy. I hope you saw that there were only minor code changes for ```spectral_filtering``` in ```utils/general.py```. 

Ok, agreed! @fsenf @freemansw1 was there any special reason why you wanted the formatting only in ```dev``` first?

**Comment by freemansw1** [comment]
I'm happy to have the formatting changes in `v2.0-dev`; I think my initial thought was that we should wait until 1.5 is feature-complete, but I don't think that's necessary.

**Review by w-k-jones — APPROVED** [review]

**Comment by w-k-jones** [comment]
Sorry for the delay catching up with this. I think reformatting v2.0-dev is better sooner rather than later, so will merge this unless anyone has any objections

**Comment by freemansw1** [comment]
Is there a way to have the tests re-run now that we've fixed them not running on this branch?

**Comment by JuliaKukulies** [comment]
Do you mean how to manually run the workflows from the other branches on ```v2.0-dev``` ?  I dont think it is possible, when we do not have any workflow files here.

**Comment by freemansw1** [comment]
Good point! It looks like I put the dockerfile in `v2.0-dev`, but not the GitHub Actions script. I cloned your PR and ran the Dockerfile manually, and the tests passed. I'm happy to merge this now, but will let @w-k-jones as it was his review.

**Pull request merged**
