### PR TITLE
All input and output based on xarray instead of Iris and pandas

### PR DESCRIPTION
**Pull request by mheikenfeld**
* Changed tobac_v1 theme to work on xarray input and output (still Iris used under the hood)
* Moved utils to subpackage folder and split up into different files
* Added decorator functions in utils/convert to allow for automatic transformation between xarray and Iris/pandas where necessary
* Added decorators to analysis and plotting and utils functions to allow for use of Iris based functions with xarray input
* Data format from now on: Input as xarray DataArrays and output as xarray Datasets (features, tracks) and xarray DataArrays (masks)
* Additional documentation in tobac_v1 theme docstrings

### CODE REVIEW

**Comment by fsenf** [comment]
Wow, what a comprehensive set of changes! I need to find a good strategy for approving all the different aspects ...

**Comment by mheikenfeld** [comment]
Yes, lots of changes in one go. But since it was all connected to consistently replace things by xarray at the top level (e.g. also in the documentation), I decided to do it as one pull request so that we can quickly head on with the new developments based on xarray in- and output...

**Comment by w-herbst** [comment]
The modules could not be found by Sphinx, so the API documentation could not be parsed. I don't know what the reason is yet.

**Comment by mheikenfeld** [comment]
> The modules could not be found by Sphinx, so the API documentation could not be parsed. I don't know what the reason is yet.

Which modules do you mean?

**Comment by w-herbst** [comment]
WARNING: [autosummary] failed to import 'tobac.analysis.analysis': no module named tobac.analysis.analysis

The same message appears for:
* 'tobac.analysis.centerofgravity'
* 'tobac.plot.plotting'
* 'tobac.themes.tobac_v1.feature_detection'
* 'tobac.themes.tobac_v1.mask_segmentation'
* 'tobac.themes.tobac_v1.tracking'
* 'tobac.utils.general'
* 'tobac.utils.mask'

But tobac.utils.convert was found.

**Comment by fsenf** [comment]
Hi all,

I can confirm that sphinx-based API rendering is also broken for my tests. I suggest to keep that as "known bug" and address this problem in an other issue or pull request. What do you think?

**Comment by fsenf** [comment]
Let us concentrate on the update of the input data interface

**Comment by fsenf** [comment]
When I run the first of our Tutorials `Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb`, I get the following error:

```
starting feature detection

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-0f1762127072> in <module>
      1 # Perform feature detection:
      2 print('starting feature detection')
----> 3 Features=tobac.themes.tobac_v1.feature_detection_multithreshold(OLR,dxy,**parameters_features)
      4 Features.to_hdf(os.path.join(savedir,'Features.h5'),'table')
      5 print('feature detection performed and saved')

~/TROPOS/tmp/tobac-dev-2020-07-09/test-env/lib/python3.7/site-packages/tobac/themes/tobac_v1/feature_detection.py in feature_detection_multithreshold(field_in, dxy, threshold, min_num, target, position_threshold, sigma_threshold, n_erosion_threshold, n_min_threshold, min_distance, feature_number_start)
     84 
     85     #convert from xarray to Iris:
---> 86     field_iris=field_in.to_iris()
     87 
     88     logging.debug('start feature detection based on thresholds')

AttributeError: 'Cube' object has no attribute 'to_iris'

```

**Comment by fsenf** [comment]
I'm afraid we're losing track here.

The issue with our issue #39 is that we have three thing at one time 1. docstrings are updated, 2. decorators and wrappers are implemented & 3. code is restructured. This makes it really hard to track the errors. At the moment, I am not sure if the best way is to step back and to reject the revision... 

However, it might be that just a minor improvement is needed and everything runs...

**Comment by fsenf** [comment]
@mheikenfeld 

I am trying to understand where you use decorators and where (and why) you are not using them.

It looks like you have only implement them for "secondary" analysis:

```
> cd tobac

tobac> ls
analysis  __init__.py  plot  __pycache__  testing.py  tests  themes  utils

tobac> grep -i 'xarray_to' */*py
analysis/analysis.py:from tobac.utils.convert import xarray_to_iris,iris_to_xarray,xarray_to_irispandas,irispandas_to_xarray
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/analysis.py:@xarray_to_irispandas
analysis/centerofgravity.py:from tobac.utils.convert import xarray_to_iris,iris_to_xarray
analysis/centerofgravity.py:@xarray_to_iris
analysis/centerofgravity.py:@xarray_to_iris
analysis/centerofgravity.py:@xarray_to_iris
analysis/centerofgravity.py:@xarray_to_iris
analysis/centerofgravity.py:@xarray_to_iris
plot/plotting.py:from tobac.utils.convert import xarray_to_iris,iris_to_xarray,xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
plot/plotting.py:@xarray_to_irispandas
utils/convert.py:def xarray_to_iris(func):
utils/convert.py:def xarray_to_irispandas(func):
utils/general.py:from .convert import xarray_to_iris, iris_to_xarray
utils/general.py:@xarray_to_iris
utils/general.py:@xarray_to_iris
utils/general.py:@xarray_to_iris
utils/general.py:# @xarray_to_iris
utils/__init__.py:from .convert import xarray_to_iris, iris_to_xarray
utils/mask.py:from tobac.utils.convert import xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:@xarray_to_iris
utils/mask.py:# @xarray_to_iris
```
**Question**: Why are decorators not taken for segmentation & feature detection? Are there any reason?

Thanks

**Comment by mheikenfeld** [comment]
@fsenf : First of all sorry for the late reply... 
I initially started off using the decorators for all functions implemented based on Iris, but then I decided to properly switch the entire interface to xarray for those core functions of the tobac_v1 theme.

 The main reason for using the decorators (and the way I implemented them) was to provide a functionality for all those functions that might be used based either Iris/pandas or xarray, depending on either being called by new code or legacy code. That's for example the case for the functions dealing with masks, which are called with Iris input from some of the functions. But that not the case for e.g. the segmentation or feature detection in the tobac_v1 theme, as they are directly called with xarray input in the new data paradigm for tobac 2, so I opted for dedicated xarray input/output there. Does that make sense?

In addition, I just used them out of convenience for all those secondary analysis functions, plotting etc. because that seemed like a temporary fix that works quite well. In the long run, however, these functions should be properly ported to xarray though...

I hope that helps a bit in explaining where and how I used the decorators, otherwise keep asking!

**Comment by mheikenfeld** [comment]
@fsenf: I agree that this is quite a complicated pull request as it contains different types of changes. However, they kind of depend on one another so it was necessary for me to suggest them all in one go as it was not possible to properly get the switch to xarray working without the change in code structure and I though it would also make sense to adapt the documentation accordingly to have it follow the code change right away.

**Comment by mheikenfeld** [comment]
> When I run the first of our Tutorials `Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb`, I get the following error:

Sorry, I realised that the tutorial notebooks still expect Iris input to these functions, because I completely forgot to make an associated pull request for the changes I made to the tutorial notebooks last month...I have made the pull request in the tutorials repository now: https://github.com/climate-processes/tobac-tutorials/pull/5

These new notebooks should work fine with the version proposed here in this pull request!

**Comment by fsenf** [comment]
Ok, after some small updates in the notebooks, everything seems to run. I included my changes into the PR https://github.com/climate-processes/tobac-tutorials/pull/5 and arranged a merge. 

In summary, we need to keep in mind that
* some functions do not run with iris anymore
* the sphinx thing need to be solved later

**Comment by mheikenfeld** [comment]
Thanks for checking and merging this  and the fixes to the notebooks, Fabian! Totally agree that we should stick to smaller PRs in the future!

**Comment by fsenf** [comment]
No worries, Max! It is great to have your input!

**Pull request merged**
